### ISSUE TITLE
Could you please provide the PDF of this article

### ISSUE THREAD

**Issue by xdheheda** [KatherineJames/AI_Drone_Vegetation_Detection#1]
I can't get the article you mentioned. Could you please provide the PDF of this article

**Comment by KatherineJames** [comment]
Unfortunately, due to the licensing of the paper, I cannot share the PDF publicly from my Github. You can access the paper from the journal through your institution via: https://doi.org/10.1111/2041-210X.13473. I am also on ResearchGate https://www.researchgate.net/profile/Katherine-James-6 if you would like to contact me about the research there.
